services:
  postgres-db:
    image: postgres:16-alpine
    container_name: asset-postgres
    environment:
      POSTGRES_DB: asset_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecretPassword123
    ports:
      - "5433:5432"
    networks:
      - asset-network

  mongo-db:
    image: mongo:7.0
    container_name: compliance-mongo
    environment:
      MONGO_INITDB_DATABASE: compliance_audit
      MONGO_INITDB_ROOT_USERNAME: root_admin
      MONGO_INITDB_ROOT_PASSWORD: MongoPassword123
    ports:
      - "27017:27017"
    networks:
      - asset-network

networks:
  asset-network:
    driver: bridge
