spring.application.name=asset-service

# 1. Primary Database Connection Profile
spring.datasource.url=jdbc:postgresql://localhost:5433/asset_management
spring.datasource.username=postgres
spring.datasource.password=SecretPassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate Automation Parameters
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Web Host Service Port
server.port=8080

# 4. MongoDB Connection Profile
# ? FIXED: Added 'data' prefix back for standard Spring Boot 3 compatibility
spring.data.mongodb.uri=mongodb://root_admin:MongoPassword123@localhost:27018/compliance_audit?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=5000&connectTimeoutMS=5000

# 5. Security Profile (Keycloak OIDC Gateway)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/asset-tracker-realm

# 6. Auto-Create MongoDB Indexes on Startup
spring.data.mongodb.auto-index-creation=true

# 7. Verbose Security Diagnostic Logs
logging.level.org.springframework.security=DEBUG

# 8. Production Monitoring & Health Infrastructure (Actuator)
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health


# 1. Enable Consul Service Discovery feature
spring.cloud.consul.discovery.enabled=true

# 2. Point to where the Consul Agent container will be running
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

# Explicitly force the service to register itself on startup
spring.cloud.consul.discovery.register=true
# Force Spring to load the global Cloud Service Discovery configuration context
spring.cloud.discovery.enabled=true

# Keeps the registration active by checking in with Consul
spring.cloud.consul.discovery.service-name=${spring.application.name}

# Force full console logging visibility
logging.level.root=INFO
logging.level.org.springframework.cloud.consul=DEBUG
logging.level.org.springframework.cloud.client.discovery=DEBUG

# Ensure standard console colors and layout are explicitly turned on
spring.output.ansi.enabled=ALWAYS
