spring.application.name=asset-service

# 1. Primary Database Connection Profile
spring.datasource.url=jdbc:postgresql://localhost:5433/asset_management
spring.datasource.username=postgres
spring.datasource.password=SecretPassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate Automation Parameters
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Web Host Service Port
server.port=8080

# 4. MongoDB Connection Profile
# Updated Spring Boot 4 Unified Connection Namespace (No 'data' prefix)
spring.mongodb.uri=mongodb://root_admin:MongoPassword123@localhost:27018/compliance_audit?authSource=admin

# 5. Security Profile (Keycloak OIDC Gateway)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/asset-tracker-realm